# Generated by Django 5.0.3 on 2024-05-30 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
