# Generated by Django 5.0.3 on 2024-05-23 13:36

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activity status'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='product/covers/', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('unavailable', 'Out of stock'), ('new', 'new'), ('preparing', 'preparing'), ('charged', 'charged'), ('Limited', 'Limited')], default='available', max_length=15, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
